### ISSUE TITLE
Hide "Run in Terminal..." and "Preferences" menu items

### ISSUE THREAD

**Issue by morgrowe** [matryer/bitbar#180]
I've only been playing around with this for a couple of minutes, so apologies if this is a duplicate question. Is it possible to hide the bottom section of a BitBar menu item?

![bitbar-hide](https://cloud.githubusercontent.com/assets/4726315/12396824/5a69735e-be01-11e5-8f66-a3c11fed5de3.jpg)

I'd like to be able to deploy an instance of BitBar, but I don't want the user to be able to play around with its configuration once it's all setup.

Keep up the great work!
Morgan

**Comment by gilbertpalau** [comment]
@morgrowe I was going to ask a question along the lines you asked, but I wanted to know how do you activate the application remotely? I have managed to deploy it to a mac remotely, create the folder with the scripts I want, but I don't know how to activate the file so it "runs" do you know a way to do this?

**Comment by morgrowe** [comment]
@gilbertpalau First, you need to create a directory to store your script(s) in. It needs to be accessible by all users (sounds like you've done that already).

Secondly, you need to create a LaunchAgent that loads BitBar at login automatically. You need to save it into /Library/LaunchAgents. This can be accomplished using defaults:

`defaults write /Library/LaunchAgents/com.ehcho.open-bitbar.plist Label -string "com.ehcho.open-bitbar"`
`defaults write /Library/LaunchAgents/com.ehcho.open-bitbar.plist RunAtLoad -bool true`
`defaults write /Library/LaunchAgents/com.ehcho.open-bitbar.plist ProgramArguments -array`
`defaults write /Library/LaunchAgents/com.ehcho.open-bitbar.plist ProgramArguments -array-add "/usr/bin/open"`
`defaults write /Library/LaunchAgents/com.ehcho.open-bitbar.plist ProgramArguments -array-add "/Applications/BitBar.app"`

Ensure permissions are correct:

`chmod 644 /Library/LaunchAgents/com.ehcho.open-bitbar.plist`
`chown root:wheel /Library/LaunchAgents/com.ehcho.open-bitbar.plist`

Finally, you need to tell BitBar where your scripts live. You can do this with this command:

`defaults write /Library/Preferences/com.matryer.BitBar.plist pluginsDirectory -string "/path/to/scripts/dir"`

Restart the machine and login as any user. Now BitBar should load after a couple of seconds, automatically loading your menu bar scripts.

Hope that helps, let me know if I've missed anything!

**Comment by mm2270** [comment]
Hi. I want to second the original request from @morgrowe. I'm impressed with the plug-ins I've been able to create with BitBar and would like to consider deploying one of them to Macs in our environment, but the presence of the submenu items that allow the end user to see the scripts or mess with settings are show-stoppers for us. Any way to hide these menu items so that the application simply shows the pre-configured plug-ins output and skips the rest?
The instructions above are helpful in getting plug-ins preconfigured, but the settings sub menus still appear in the menu item.

**Comment by matryer** [comment]
Enough people have raised this for me to take a closer look at a solution. I’ll have a think this week.

Thanks
Mat
On 1 February 2016 at 17:59:00, Mike M (notifications@github.com) wrote:

Hi. I want to second the original request from @morgrowe. I'm impressed with the plug-ins I've been able to create with BitBar and would like to consider deploying one of them to Macs in our environment, but the presence of the submenu items that allow the end user to see the scripts or mess with settings are show-stoppers for us. Any way to hide these menu items so that the application simply shows the pre-configured plug-ins output and skips the rest?
The instructions above are helpful in getting plug-ins preconfigured, but the settings sub menus still appear in the menu item.

**Comment by mm2270** [comment]
Thanks for the quick reply! And thanks for considering the request. 

Mike

**Comment by morgrowe** [comment]
Excellent, thank you @matryer!

**Comment by gilbertpalau** [comment]
@morgrowe I followed your steps and was able to deploy and activate (without rebooting) this is the script I am using:

`# BitBar Launch v0.001
#
# This was put together by @morgrowe at 
# https://github.com/matryer/bitbar/issues/180#issuecomment-175888167
#
# Create a LaunchAgent that loads BitBar at login automatically and specify where plugins are installed.

defaults write /Library/LaunchAgents/com.ehcho.open-bitbar.plist Label -string "com.ehcho.open-bitbar"
defaults write /Library/LaunchAgents/com.ehcho.open-bitbar.plist RunAtLoad -bool true
defaults write /Library/LaunchAgents/com.ehcho.open-bitbar.plist ProgramArguments -array
defaults write /Library/LaunchAgents/com.ehcho.open-bitbar.plist ProgramArguments -array-add "/usr/bin/open"
defaults write /Library/LaunchAgents/com.ehcho.open-bitbar.plist ProgramArguments -array-add "/Applications/Utilities/BitBar.app"
defaults write /Library/Preferences/com.matryer.BitBar.plist pluginsDirectory -string "/Library/ETS/bitbar-plugins"

# Apply Permissions
chmod 644 /Library/LaunchAgents/com.ehcho.open-bitbar.plist
chown root:wheel /Library/LaunchAgents/com.ehcho.open-bitbar.plist

# Launch Bit-Bar
/usr/bin/open /Applications/Utilities/BitBar.app`

I use FileWave to deploy, this is how the file contents look: http://i.imgur.com/9IwZVUP.png

Thanks!! Works great.  At least a good work around until @matryer updates.

**Comment by willyt** [comment]
The menu item convention is that you see extra stuff if you alt click on it. E.g. alt click wifi to show extra stats. Maybe an easy way to do it is if these items could be hidden unless you alt click?

**Comment by matryer** [comment]
Yes @willyt, I like that

**Comment by morgrowe** [comment]
@willyt @matryer I like the idea too, but I'd really appreciate a way to hide those menu items regardless of whether or not the option key is depressed when the menu bar icon is clicked.

If I were deploying BitBar to a Mac where adults are the main user(s), this would be a great solution, but when deploying to a Mac where kids are the main user(s), I fear it would only be a matter of time before they work out the alt+click and start messing around with BitBar's configuration.

**Comment by willyt** [comment]
I have been reading the code a little in my spare time and I think that the alt + click option would be fairly easy to add quickly just now. In the long run it would be nice to do as @morgrowe and have a preference which permanently disabled those items and the only way to re-enable them would be with a `defaults write com.matryer.BitBar enableDevMode True` command or something, but I think its quite a bit more work for someone to add this feature?

**Comment by mm2270** [comment]
Agreed with @morgrowe. It would be good to have an Option/Alt click (default?) setting to show the Preferences submenu at the bottom instead of them always being there, but I would also be looking for a way to disable that sub-menu regardless of modifier keys being pressed. My thought is to have BitBar use a boolean setting in the plist, i.e, `defaults write /Library/Preferences/com.matryer.bitbar.plist disablePrefsMenu -bool true` or something along those lines. Note that I'm thinking of a global plist, as in my example above -  `/Library/Preferences/`, as opposed to a user level setting `~/Library/Preferences/` since I've found that BitBar will respect the global plist perfectly fine, and that could work well in managed environments.

**Comment by su-hy** [comment]
Hey... 4 years later, is there an option to hide "Run in Terminal..." and Preferences?

**Comment by gingerbeardman** [comment]
> Hey... 4 years later, is there an option to hide "Run in Terminal..." and Preferences?

Use the "BitBarDistro" build, available since 22 Feb 2016.

**Comment by su-hy** [comment]
Thanks a lot for a quick reply. Will try it tomorrow!

**Comment by su-hy** [comment]
Maybe someone will find this useful, but in my testing running the command:
defaults write com.matryer.BitBar userConfigDisabled -bool true
With normal BitBar also disables "Run in Terminal" and Preferences.
