### ISSUE TITLE
Default text color is illegible on menubar dark theme

### ISSUE THREAD

**Issue by malteo** [matryer/bitbar#19]
It should be white on black

**Comment by malteo** [comment]
![screenshot 2015-11-12 12 47 20](https://cloud.githubusercontent.com/assets/80266/11117633/b067bd1a-893b-11e5-85e7-2e222a7eed1d.png)

**Comment by Derimagia** [comment]
What plugin is this? Because colors are manually entered by plugin authors, I don't think this is the fault of the Bitbar app.

I made a pull request so plugins can easily get this information:
https://github.com/matryer/bitbar/pull/155

If this pull request is accepted this can be fixed by the plugin author.

**Comment by tresni** [comment]
This seems fixed for me.  I'm getting white text for default text colors when using the Dark mode.  Additionally plugins now can get dark mode info thanks to #155.

**Comment by iosdeveloper** [comment]
Please close this issue.
