### ISSUE TITLE
Couldn`t posix_spawn: error 8

### ISSUE THREAD

**Issue by offshore-cv** [matryer/bitbar#196]
And 2 yellow triagle in status bar

**Comment by gilbertpalau** [comment]
If you downloaded the script by Download Linked File As, it will download the HTML... you need to download the script by clicking on the Get Plugin button and copy and pasting  the code on a text editor like Atom and saving it to the folder for your plugins.

I just tried this because I had gotten the same error and that is the result.

**Comment by offshore-cv** [comment]
Thanks bro. Thats works! 
))

**Comment by gilbertpalau** [comment]
yw

**Comment by mrjcleaver** [comment]
Also check your system load, if it's too high you might not be able to launch a legitimately downloaded plugin.

**Comment by ecnepsnai** [comment]
This will also happen if you're missing an interpreter at the head of the file (I.E. `#!/bin/bash` or `#!/usr/bin/ruby`)

**Comment by taldeguer** [comment]
hi, i've installed the slack plugin and it seems to work fine once the python version problem solved on OSX but it keeps showing a yellow triangle saying posix_spawn error 8. I have a shebang .
any idea on how to investigate ?

**Comment by gingerbeardman** [comment]
Is the plugin marked as executable?

**Comment by taldeguer** [comment]
yes it is, i solved (more like a workaround)  it using a simple bash wrapper. so i can have a slack notification in my bar

**Comment by taldeguer** [comment]
i cannot click the icon once launched though. i have to install some other plugin so i can click refresh when needed

**Comment by taldeguer** [comment]
@gingerbeardman Did you manage to make it work ?

**Comment by ApopheniaPays** [comment]
This is becoming a very serious problem for me. I was relying on bitbar and now I can't use it at all. 

I didn't download my script, I wrote it by hand, and it does have the interpreter as the first line. In fact, it seems completely random as to whether I get this error or not. A script that has worked fine for years suddenly gets this error when I change it, but when I revert the changes back, the error doesn't go away. 

It appears related to trying to put a duration in the script name... like scriptName.2s.sh instead of scriptName.sh. This causes the problem to start. However, renaming it back doesn't solve the problem, neither does rebooting my computer or reinstalling Bitbar. 

At this point it appears Bitbar doesn't work at all for me, which is frustrating, as I was relying on it.

**Comment by ApopheniaPays** [comment]
For anyone finding this in the future with the same problem, I found a solution not yet mentioned: 

xattr -d com.apple.quarantine /path/to/script.sh

Fill in the correct script path for /path/to/script.sh and enter this in terminal. It's OS X's "helpful" quarantine system preventing your script from running.
