### ISSUE TITLE
Refresh at login (or any specific event)

### ISSUE THREAD

**Issue by ffittschen** [matryer/bitbar#202]
Hi,
I use quite some BitBar plugins, which have a long refresh time (> couple of hours), but I would like them to be refreshed, when my MacBook "wakes up". So e.g. I'm at home and my current network location is displayed using BitBar with 2h refresh time. Then I just close the lid, drive to work and open my MacBook again. This would be a perfect "event" to refresh this plugin.

Is this somehow feasible?

**Comment by matryer** [comment]
I think this is actually implemented in the latest build. It was done because it sleeping was confusing BitBar. Can you install the latest version and let me know if this works for you? https://github.com/matryer/bitbar/releases/tag/v1.5.0-beta1 <https://github.com/matryer/bitbar/releases/tag/v1.5.0-beta1>

**Comment by ffittschen** [comment]
@matryer Wow, that was a fast reply 😄

I just tried it with some other plugin and it works perfectly, thanks 👍🏻
