### ISSUE TITLE
Create HomeBrew recipe

### ISSUE THREAD

**Issue by sergiotapia** [matryer/bitbar#206]
I normally install things using Homebrew on El Capitan/Yosemite.

Would love to be able to:

`brew install bitbar`

**Comment by matryer** [comment]
Then it's your lucky day: https://github.com/matryer/bitbar#get-started 

Although I'm not sure how it selects which version to install?

**Comment by pallih** [comment]
The cask "tap" lives here: https://github.com/caskroom/homebrew-cask/blob/master/Casks/bitbar.rb

Instructions on how to update a tap: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md

**Comment by tresni** [comment]
@matryer cask's aren't automatically updated, though the `appcast` allows you to check for updates.  Released, stable versions go to caskroom/homebrew-cask as linked by @pallih .  Beta versions go to [caskroom/versions](github.com/caskroom/homebrew-versions).  I created a [bitbar-beta](https://github.com/caskroom/homebrew-versions/blob/master/Casks/bitbar-beta.rb) cask which tracks prereleases :)

```
brew tap caskroom/versions
brew cask install bitbar-beta
```

BitBar isn't appropriate for Homebrew itself since it would amount to a [formula that builds an .app](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#stuff-that-builds-a-app).  Caskroom is the appropriate place for BitBar.

**Comment by matryer** [comment]
@iosdeveloper can we close this now since the cask is updated?
