### ISSUE TITLE
1.8 crashes if a loading plugin is refreshed

### ISSUE THREAD

**Issue by vogonistic** [matryer/bitbar#282]
Steps to reproduce:
1. Refresh plugins with `Cmd-R`
2. While at least one plugin is loading, refresh the plugins again with `Cmd-R`
3. Crash

If NSZombies are turned on, this message is dumped:
`2016-03-16 12:13:41.790 BitBar[12034:2214293] *** -[ExecutablePlugin setContent:]: message sent to deallocated instance 0x6180001041d0`

The problem seems to be that self is deallocated at [ExecutablePlugin.m#L48](https://github.com/matryer/bitbar/blob/master/App/BitBar/ExecutablePlugin.m#L48). One solution would be to create a new strong reference to self until after execution, or to use a `__weak` reference and `NSTask.terminationHandler`.

I also don't see how `if (weakSelf) {` will work with a `__unsafe_unretained` since the main difference between `__unsafe_unretained` and `__weak` is that `__weak` is set to nil when the reference is deallocated while `__unsafe_unretained` still points to the same address. [ExecutablePlugin.m#L83](https://github.com/matryer/bitbar/blob/master/App/BitBar/ExecutablePlugin.m#L83)

Could we increase the deployment target to 10.7 so that `__weak` can be used?

**Comment by mm2270** [comment]
I've been wondering myself why the deployment target is set to 10.6. I understand that @matryer may want to make it available to as many users as possible, but the numbers of 10.6 Macs these days are kind of low I think, not to mention unsafe to even be using on the internet at this point. 10.7 seems like a very generous low barrier as the minimum OS target to me. That's still 4 major releases behind current. Just my 2¢ though.

**Comment by iosdeveloper** [comment]
@mm2270 #204 (just saying)

**Comment by matryer** [comment]
I'm happy to go to `10.7` unless anybody has any objections?

**Comment by tresni** [comment]
So funny enough, this is the issue that I wasn't sure could happen.  We moved the `__strong` reference before [ExecutablePlugin.m#L81](https://github.com/matryer/bitbar/blob/master/App/BitBar/ExecutablePlugin.m#L81) to counter it but that didn't make it in the final merge for some reason.  I believe that would resolve the issue as it would hold the `__strong` until after the `dispatch_sync` is completed.  Since `dispatch_sync` returns on completion I'm not worried about it holding the reference.

The `if (weakSelf)` check works as it's looking to see if we have been deallocated right before entering the block.  By getting `weakSelf` and then (almost) immediately taking a `__strong` relationship to it, I believe we are preventing the plugin from deallocating within the block.  We just can't use `self` directly as it creates reference counts from being accessed within the blocks.  Going to give this a shot and will report back shortly.

**Comment by vogonistic** [comment]
The weakSelf check doesn't work because a `__unsafe_unretained` variable isn't set to nil when the object is deallocated. It's the main difference with `__weak`.

The thing that feels weird is that the object is deallocated while `[task waitUntilExit];` is executing. I assumed that running a method on an object would keep a strong reference to self during execution, but that's obviously not the case.

Maybe there is another way we can do this, without using `__unsafe_unretained`, if we keep a reference to the actively running task and if we refresh and reload, we'll interrupt it and clean it up properly.

**Comment by tresni** [comment]
Actually I'm having it get deallocated all over the place even making the changes I thought would prevent that :)  So yeah, safe (and definitely easy) measure is to just target 1.7 and get the auto-nilling of `weak`.  I just tested that, works great :)
