### ISSUE TITLE
I do not get an event with python 

### ISSUE THREAD

**Issue by tanrax** [matryer/bitbar#323]
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys

if len(sys.argv) > 1:
    command = sys.argv[1]
    if command == 'open':
        print('click')

print(len(sys.argv))
        
print('Update | bash={0} param1={1} refresh=true terminal=false'.format(sys.argv[0], 'open'))
```

**Comment by Mattias-** [comment]
What do you expect to happen? It seems like your logic to "communicate" back to the plugin is incorrect since the spawned script when you click Update will run outside the context of bitbar.

**Comment by tanrax** [comment]
Print text 'Open' when I click Update.
As it should do then?

Thanks!

**Comment by iosdeveloper** [comment]
When you click, your script will be executed twice. Once as `bash=$0` with parameters and once without parameters (because you set `refresh=true`). Only the second execution without parameters will be rendered. Please take a look at the plugins in matryer/bitbar-plugins to see how they handle it.
I don't think we will change this behavior as it would break existing plugins.
